# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fc589a62ef726e6a89c030b3099e34bf23b9ab40c21d6044312e2edd648dd507aea85c1710ce639ae17010b170090cced66be92a7e92c9d797d8aa14052aed1

test:
  secret_key_base: ea6655998b809454114333cbbda1f07eafc899df52593e9b596c7671526df02846041ccb26fe63cecc2000f596aa1f38754ea9f7fa360a3d15b28da6786e8be7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
